let industries = [
  "Information Technology",
  "Healthcare and Pharmaceuticals",
  "Finance and Banking",
  "Automotive and Automotive Manufacturing",
  "Food Service and Restaurants",
  "Education",
  "Energy and Environment",
  "Real Estate",
  "Sports and Entertainment",
  "Health and Beauty",
  "Pet Care",
  "Logistics and Transportation",
  "Agriculture and Food",
  "Fashion and Online Retail",
  "Manufacturing Industry",
  "Advertising and Marketing",
  "Digital Entertainment Industry",
  "Processing Industry",
  "Athletics and Sports",
  "Telecommunications and Communications",
  "Aerospace and Defense",
  "Travel and Tourism",
  "Construction",
  "Media and Broadcasting",
  "Legal Services",
  "Retail",
  "Gaming Industry",
  "Music and Music Production",
  "Pharmaceuticals",
  "Biotechnology",
];

industries.sort();

export default industries;
