const regions = [
  {
    key: "Asia",
    sub: [
      "United Arab Emirates",
      "Afghanistan",
      "Armenia",
      "Azerbaijan",
      "Bangladesh",
      "Bhutan",
      "Brunei Darussalam",
      "China",
      "Georgia",
      "Hong Kong",
      "India",
      "Indonesia",
      "Israel",
      "Iraq",
      "Iran, Islamic Republic of",
      "Jordan",
      "Japan",
      "Kazakhstan",
      "Cambodia",
      "Kyrgyzstan",
      "South Korea",
      "Kuwait",
      "Laos",
      "Lebanon",
      "Sri Lanka",
      "Myanmar",
      "Mongolia",
      "Macao",
      "Maldives",
      "Malaysia",
      "Nepal",
      "Oman",
      "Pakistan",
      "Palestine, State of",
      "Philippines",
      "Qatar",
      "Saudi Arabia",
      "Singapore",
      "Syria",
      "Thailand",
      "Tajikistan",
      "Timor-Leste",
      "Turkmenistan",
      "Turkey",
      "Taiwan",
      "Uzbekistan",
      "Vietnam",
      "Yemen",
    ],
  },
  {
    key: "Europe",
    sub: [
      "Andorra",
      "Albania",
      "Austria",
      "Bosnia and Herzegovina",
      "Belgium",
      "Bulgaria",
      "Belarus",
      "Switzerland",
      "Czech Republic",
      "Germany",
      "Denmark",
      "Estonia",
      "Spain",
      "Finland",
      "France",
      "United Kingdom",
      "Guernsey",
      "Greece",
      "Croatia",
      "Hungary",
      "Ireland",
      "Isle of Man",
      "Iceland",
      "Italy",
      "Jersey",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Latvia",
      "Monaco",
      "Moldova, Republic of",
      "Montenegro",
      "Macedonia, the Former Yugoslav Republic of",
      "Malta",
      "Netherlands",
      "Norway",
      "Poland",
      "Portugal",
      "Romania",
      "Serbia",
      "Russia",
      "Sweden",
      "Slovenia",
      "Svalbard and Jan Mayen",
      "Slovakia",
      "San Marino",
      "Vatican City",
      "Kosovo",
    ],
  },
  {
    key: "Africa",
    sub: [
      "Angola",
      "Burkina Faso",
      "Burundi",
      "Benin",
      "Botswana",
      "Central African Republic",
      "Congo, Republic of the",
      "Congo, Democratic Republic of the",
      "Comoros",
      "Cape Verde",
      "Djibouti",
      "Algeria",
      "Egypt",
      "Western Sahara",
      "Eritrea",
      "Ethiopia",
      "Gabon",
      "Ghana",
      "Gambia",
      "Guinea",
      "Equatorial Guinea",
      "Guinea-Bissau",
      "Kenya",
      "Lesotho",
      "Liberia",
      "Libya",
      "Morocco",
      "Madagascar",
      "Mali",
      "Mauritania",
      "Mauritius",
      "Malawi",
      "Mozambique",
      "Namibia",
      "Niger",
      "Nigeria",
      "Reunion",
      "Rwanda",
      "Seychelles",
      "Sudan",
      "South Sudan",
      "Saint Helena",
      "Sierra Leone",
      "Senegal",
      "Somalia",
      "Sao Tome and Principe",
      "Swaziland",
      "Chad",
      "Togo",
      "Tunisia",
      "Tanzania, United Republic of",
      "Uganda",
      "Mayotte",
      "South Africa",
      "Zambia",
      "Zimbabwe",
    ],
  },
  {
    key: "North America",
    sub: [
      "Antigua and Barbuda",
      "Anguilla",
      "Aruba",
      "Barbados",
      "Bermuda",
      "Bahamas",
      "Belize",
      "Canada",
      "Costa Rica",
      "Cuba",
      "Curaçao",
      "Christmas Island",
      "Cayman Islands",
      "Dominica",
      "Dominican Republic",
      "Falkland Islands (Malvinas)",
      "Grenada",
      "Greenland",
      "Guadeloupe",
      "Guatemala",
      "Honduras",
      "Haiti",
      "Jamaica",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Martinique",
      "Montserrat",
      "Mexico",
      "Nicaragua",
      "Panama",
      "Saint Pierre and Miquelon",
      "Puerto Rico",
      "El Salvador",
      "Sint Maarten (Dutch part)",
      "Turks and Caicos Islands",
      "Trinidad and Tobago",
      "United States",
      "Saint Vincent and the Grenadines",
      "Virgin Islands, British",
      "Virgin Islands, U.S.",
    ],
  },
  {
    key: "South America",
    sub: [
      "Argentina",
      "Bolivia",
      "Brazil",
      "Chile",
      "Colombia",
      "Ecuador",
      "Falkland Islands (Malvinas)",
      "Guyana",
      "Peru",
      "Paraguay",
      "Suriname",
      "Uruguay",
      "Venezuela",
      "French Guiana",
    ],
  },
  {
    key: "Oceania",
    sub: [
      "Australia",
      "Fiji",
      "Micronesia, Federated States of",
      "Guam",
      "Kiribati",
      "Marshall Islands",
      "Northern Mariana Islands",
      "New Caledonia",
      "Norfolk Island",
      "Nauru",
      "Niue",
      "New Zealand",
      "French Polynesia",
      "Papua New Guinea",
      "Palau",
      "Pitcairn",
      "Solomon Islands",
      "Tokelau",
      "Timor-Leste",
      "Tonga",
      "Tuvalu",
      "Vanuatu",
      "Wallis and Futuna",
      "Samoa",
    ],
  },
];

const regions2 = [
  {
    key: "East Asia",
    sub: ["North Korea", "Mongolia", "Japan", "China", "South Korea", "Taiwan"],
  },
  {
    key: "Southeast Asia",
    sub: [
      "Brunei",
      "Myanmar",
      "Malaysia",
      "Singapore",
      "Thailand",
      "Vietnam",
      "Cambodia",
      "East Timor",
      "Philippines",
      "Indonesia",
      "Laos",
    ],
  },
  {
    key: "South Asia",
    sub: [
      "Maldives",
      "Afghanistan",
      "Bhutan",
      "India",
      "Nepal",
      "Bangladesh",
      "Pakistan",
      "Sri Lanka",
    ],
  },
  {
    key: "Central Asia",
    sub: [
      "Tajikistan",
      "Kazakhstan",
      "Kyrgyzstan",
      "Turkmenistan",
      "Uzbekistan",
    ],
  },
  {
    key: "North Asia",
    sub: ["Russia"],
  },
  {
    key: "North Africa",
    sub: [
      "Egypt",
      "Morocco",
      "Sudan",
      "Algeria",
      "Libya",
      "Western Sahara",
      "Tunisia",
    ],
  },
  {
    key: "East Africa",
    sub: [
      "Burundi",
      "Eritrea",
      "Ethiopia",
      "Kenya",
      "Malawi",
      "Mauritius",
      "Mozambique",
      "South Sudan",
      "Réunion",
      "Comoros",
      "Djibouti",
      "Rwanda",
      "Seychelles",
      "Somalia",
      "Madagascar",
      "Tanzania",
      "Zambia",
      "Zimbabwe",
      "Uganda",
    ],
  },
  {
    key: "Southern Africa",
    sub: ["South Africa", "Botswana", "Lesotho", "Namibia", "Swaziland"],
  },
  {
    key: "North America",
    sub: ["Canada", "United States", "Mexico"],
  },
  {
    key: "South America",
    sub: [
      "Argentina",
      "Bolivia",
      "Brazil",
      "Chile",
      "Colombia",
      "Ecuador",
      "Guyana",
      "Paraguay",
      "Peru",
      "Suriname",
      "Uruguay",
      "Venezuela",
    ],
  },
  {
    key: "Central America",
    sub: [
      "Antigua and Barbuda",
      "Bahamas",
      "Barbados",
      "Belize",
      "Costa Rica",
      "Cuba",
      "Dominican Republic",
      "Dominica",
      "El Salvador",
      "Grenada",
      "Guatemala",
      "Haiti",
      "Honduras",
      "Jamaica",
      "Nicaragua",
      "Panama",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Vincent and the Grenadines",
      "Trinidad and Tobago",
    ],
  },
  {
    key: "Northern Europe",
    sub: [
      "Estonia",
      "Lithuania",
      "Ireland",
      "United Kingdom",
      "Iceland",
      "Latvia",
      "Norway",
      "Denmark",
      "Sweden",
      "Finland",
    ],
  },
  {
    key: "Southern Europe",
    sub: [
      "Greece",
      "Bosnia and Herzegovina",
      "North Macedonia",
      "Andorra",
      "Bosnia",
      "Montenegro",
      "Serbia",
      "Albania",
      "Portugal",
      "Spain",
      "Italy",
      "Croatia",
      "Malta",
      "San Marino",
      "Slovenia",
      "Vatican City",
    ],
  },
  {
    key: "Western and Central Europe",
    sub: [
      "Austria",
      "Monaco",
      "Switzerland",
      "Belgium",
      "Germany",
      "Liechtenstein",
      "Netherlands",
      "Luxembourg",
      "France",
      "Czech Republic",
      "Slovakia",
      "Belarus",
      "Bulgaria",
      "Hungary",
      "Poland",
      "Russia",
      "Ukraine",
    ],
  },
  {
    key: "Eastern Europe",
    sub: [
      "Moldova",
      "Poland",
      "Romania",
      "Slovakia",
      "Belarus",
      "Bulgaria",
      "Czech Republic",
      "Russia",
      "Hungary",
      "Ukraine",
    ],
  },
  {
    key: "West Africa",
    sub: [
      "Burkina Faso",
      "Cape Verde",
      "Gambia",
      "Benin",
      "Ivory Coast",
      "Ghana",
      "Guinea",
      "Guinea-Bissau",
      "Liberia",
      "Mali",
      "Saint Helena",
      "Senegal",
      "Sierra Leone",
      "Togo",
    ],
  },
  {
    key: "Central Africa",
    sub: [
      "Angola",
      "Cameroon",
      "Central African Republic",
      "Chad",
      "Democratic Republic of the Congo",
      "Republic of the Congo",
      "Equatorial Guinea",
      "Gabon",
      "Sao Tome and Principe",
    ],
  },
  {
    key: "West Africa",
    sub: [
      "Burkina Faso",
      "Cape Verde",
      "Gambia",
      "Benin",
      "Ivory Coast",
      "Ghana",
      "Guinea",
      "Guinea-Bissau",
      "Liberia",
      "Mali",
      "Saint Helena",
      "Senegal",
      "Sierra Leone",
      "Togo",
    ],
  },
  {
    key: "North Africa",
    sub: [
      "Algeria",
      "Egypt",
      "Libya",
      "Morocco",
      "Sudan",
      "Tunisia",
      "Western Sahara",
    ],
  },
  {
    key: "West Asia",
    sub: [
      "Armenia",
      "Azerbaijan",
      "Bahrain",
      "Cyprus",
      "Georgia",
      "Iraq",
      "Israel",
      "Jordan",
      "Kuwait",
      "Lebanon",
      "Oman",
      "Palestine",
      "Qatar",
      "Saudi Arabia",
      "Syria",
      "Turkey",
      "United Arab Emirates",
      "Yemen",
    ],
  },
  {
    key: "Central Asia",
    sub: [
      "Kazakhstan",
      "Kyrgyzstan",
      "Tajikistan",
      "Turkmenistan",
      "Uzbekistan",
    ],
  },
  {
    key: "East Europe",
    sub: [
      "Belarus",
      "Bulgaria",
      "Czech Republic",
      "Hungary",
      "Moldova",
      "Poland",
      "Romania",
      "Russia",
      "Slovakia",
      "Ukraine",
    ],
  },
  {
    key: "West Europe",
    sub: [
      "Austria",
      "Belgium",
      "France",
      "Germany",
      "Liechtenstein",
      "Luxembourg",
      "Monaco",
      "Netherlands",
      "Switzerland",
    ],
  },
  {
    key: "East Europe",
    sub: ["Estonia", "Latvia", "Lithuania", "Russia"],
  },
  {
    key: "Southern Europe",
    sub: [
      "Albania",
      "Andorra",
      "Bosnia and Herzegovina",
      "Croatia",
      "Gibraltar",
      "Greece",
      "Italy",
      "Malta",
      "Montenegro",
      "North Macedonia",
      "Portugal",
      "San Marino",
      "Serbia",
      "Slovenia",
      "Spain",
      "Vatican City",
    ],
  },
  {
    key: "Western Europe",
    sub: [
      "Austria",
      "Belgium",
      "France",
      "Germany",
      "Liechtenstein",
      "Luxembourg",
      "Monaco",
      "Netherlands",
      "Switzerland",
    ],
  },
  {
    key: "Central Europe",
    sub: [
      "Austria",
      "Croatia",
      "Czech Republic",
      "Germany",
      "Hungary",
      "Poland",
      "Slovakia",
      "Slovenia",
    ],
  },
  {
    key: "Eastern Europe",
    sub: [
      "Belarus",
      "Bulgaria",
      "Estonia",
      "Latvia",
      "Lithuania",
      "Moldova",
      "Romania",
      "Russia",
      "Ukraine",
    ],
  },
  {
    key: "Middle Africa",
    sub: [
      "Angola",
      "Cameroon",
      "Central African Republic",
      "Chad",
      "Congo",
      "Democratic Republic of the Congo",
      "Equatorial Guinea",
      "Gabon",
      "Sao Tome and Principe",
    ],
  },
  {
    key: "North Africa",
    sub: [
      "Algeria",
      "Egypt",
      "Libya",
      "Morocco",
      "Sudan",
      "Tunisia",
      "Western Sahara",
    ],
  },
  {
    key: "South Asia",
    sub: [
      "Afghanistan",
      "Bangladesh",
      "Bhutan",
      "India",
      "Iran",
      "Maldives",
      "Nepal",
      "Pakistan",
      "Sri Lanka",
    ],
  },
  {
    key: "Southeast Asia",
    sub: [
      "Brunei",
      "Cambodia",
      "East Timor",
      "Indonesia",
      "Laos",
      "Malaysia",
      "Myanmar",
      "Philippines",
      "Singapore",
      "Thailand",
      "Vietnam",
    ],
  },
  {
    key: "East Asia",
    sub: [
      "China",
      "Hong Kong",
      "Japan",
      "Macao",
      "Mongolia",
      "North Korea",
      "South Korea",
      "Taiwan",
    ],
  },
  {
    key: "West Asia",
    sub: [
      "Bahrain",
      "Cyprus",
      "Georgia",
      "Iraq",
      "Israel",
      "Jordan",
      "Kuwait",
      "Lebanon",
      "Oman",
      "Palestine",
      "Qatar",
      "Saudi Arabia",
      "Syria",
      "Turkey",
      "United Arab Emirates",
      "Yemen",
    ],
  },
  {
    key: "North America",
    sub: [
      "Antigua and Barbuda",
      "Bahamas",
      "Barbados",
      "Belize",
      "Canada",
      "Costa Rica",
      "Cuba",
      "Dominica",
      "Dominican Republic",
      "El Salvador",
      "Grenada",
      "Guatemala",
      "Haiti",
      "Honduras",
      "Jamaica",
      "Mexico",
      "Nicaragua",
      "Panama",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Vincent and the Grenadines",
      "Trinidad and Tobago",
      "United States",
    ],
  },
  {
    key: "South America",
    sub: [
      "Argentina",
      "Bolivia",
      "Brazil",
      "Chile",
      "Colombia",
      "Ecuador",
      "Guyana",
      "Paraguay",
      "Peru",
      "Suriname",
      "Uruguay",
      "Venezuela",
    ],
  },
  {
    key: "Oceania",
    sub: [
      "Australia",
      "Fiji",
      "Kiribati",
      "Marshall Islands",
      "Micronesia",
      "Nauru",
      "New Zealand",
      "Palau",
      "Papua New Guinea",
      "Samoa",
      "Solomon Islands",
      "Tonga",
      "Tuvalu",
      "Vanuatu",
    ],
  },
];

export default regions;
