const regions = [
  {
    key: "Asia",
    sub: [
      "United Arab Emirates",
      "Afghanistan",
      "Armenia",
      "Azerbaijan",
      "Bangladesh",
      "Bhutan",
      "Brunei Darussalam",
      "China",
      "Georgia",
      "Hong Kong",
      "India",
      "Indonesia",
      "Israel",
      "Iraq",
      "Iran, Islamic Republic of",
      "Jordan",
      "Japan",
      "Kazakhstan",
      "Cambodia",
      "Kyrgyzstan",
      "South Korea",
      "Kuwait",
      "Laos",
      "Lebanon",
      "Sri Lanka",
      "Myanmar",
      "Mongolia",
      "Macao",
      "Maldives",
      "Malaysia",
      "Nepal",
      "Oman",
      "Pakistan",
      "Palestine, State of",
      "Philippines",
      "Qatar",
      "Saudi Arabia",
      "Singapore",
      "Syria",
      "Thailand",
      "Tajikistan",
      "Timor-Leste",
      "Turkmenistan",
      "Turkey",
      "Taiwan",
      "Uzbekistan",
      "Vietnam",
      "Yemen",
    ],
  },
  {
    key: "Europe",
    sub: [
      "Andorra",
      "Albania",
      "Austria",
      "Bosnia and Herzegovina",
      "Belgium",
      "Bulgaria",
      "Belarus",
      "Switzerland",
      "Czech Republic",
      "Germany",
      "Denmark",
      "Estonia",
      "Spain",
      "Finland",
      "France",
      "United Kingdom",
      "Guernsey",
      "Greece",
      "Croatia",
      "Hungary",
      "Ireland",
      "Isle of Man",
      "Iceland",
      "Italy",
      "Jersey",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Latvia",
      "Monaco",
      "Moldova, Republic of",
      "Montenegro",
      "Macedonia, the Former Yugoslav Republic of",
      "Malta",
      "Netherlands",
      "Norway",
      "Poland",
      "Portugal",
      "Romania",
      "Serbia",
      "Russia",
      "Sweden",
      "Slovenia",
      "Svalbard and Jan Mayen",
      "Slovakia",
      "San Marino",
      "Vatican City",
      "Kosovo",
    ],
  },
  {
    key: "Africa",
    sub: [
      "Angola",
      "Burkina Faso",
      "Burundi",
      "Benin",
      "Botswana",
      "Central African Republic",
      "Congo, Republic of the",
      "Congo, Democratic Republic of the",
      "Comoros",
      "Cape Verde",
      "Djibouti",
      "Algeria",
      "Egypt",
      "Western Sahara",
      "Eritrea",
      "Ethiopia",
      "Gabon",
      "Ghana",
      "Gambia",
      "Guinea",
      "Equatorial Guinea",
      "Guinea-Bissau",
      "Kenya",
      "Lesotho",
      "Liberia",
      "Libya",
      "Morocco",
      "Madagascar",
      "Mali",
      "Mauritania",
      "Mauritius",
      "Malawi",
      "Mozambique",
      "Namibia",
      "Niger",
      "Nigeria",
      "Reunion",
      "Rwanda",
      "Seychelles",
      "Sudan",
      "South Sudan",
      "Saint Helena",
      "Sierra Leone",
      "Senegal",
      "Somalia",
      "Sao Tome and Principe",
      "Swaziland",
      "Chad",
      "Togo",
      "Tunisia",
      "Tanzania, United Republic of",
      "Uganda",
      "Mayotte",
      "South Africa",
      "Zambia",
      "Zimbabwe",
    ],
  },
  {
    key: "North America",
    sub: [
      "Antigua and Barbuda",
      "Anguilla",
      "Aruba",
      "Barbados",
      "Bermuda",
      "Bahamas",
      "Belize",
      "Canada",
      "Costa Rica",
      "Cuba",
      "Curaçao",
      "Christmas Island",
      "Cayman Islands",
      "Dominica",
      "Dominican Republic",
      "Falkland Islands (Malvinas)",
      "Grenada",
      "Greenland",
      "Guadeloupe",
      "Guatemala",
      "Honduras",
      "Haiti",
      "Jamaica",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Martinique",
      "Montserrat",
      "Mexico",
      "Nicaragua",
      "Panama",
      "Saint Pierre and Miquelon",
      "Puerto Rico",
      "El Salvador",
      "Sint Maarten (Dutch part)",
      "Turks and Caicos Islands",
      "Trinidad and Tobago",
      "United States",
      "Saint Vincent and the Grenadines",
      "Virgin Islands, British",
      "Virgin Islands, U.S.",
    ],
  },
  {
    key: "South America",
    sub: [
      "Argentina",
      "Bolivia",
      "Brazil",
      "Chile",
      "Colombia",
      "Ecuador",
      "Falkland Islands (Malvinas)",
      "Guyana",
      "Peru",
      "Paraguay",
      "Suriname",
      "Uruguay",
      "Venezuela",
      "French Guiana",
    ],
  },
  {
    key: "Oceania",
    sub: [
      "Australia",
      "Fiji",
      "Micronesia, Federated States of",
      "Guam",
      "Kiribati",
      "Marshall Islands",
      "Northern Mariana Islands",
      "New Caledonia",
      "Norfolk Island",
      "Nauru",
      "Niue",
      "New Zealand",
      "French Polynesia",
      "Papua New Guinea",
      "Palau",
      "Pitcairn",
      "Solomon Islands",
      "Tokelau",
      "Timor-Leste",
      "Tonga",
      "Tuvalu",
      "Vanuatu",
      "Wallis and Futuna",
      "Samoa",
    ],
  },
];

export default regions;
